### ISSUE TITLE
IVS Broadcast Client Issues

### ISSUE THREAD

**Issue by alpgokcek** [aws-samples/amazon-ivs-broadcast-web-demo#21]
Hello,
We want to use the IVS service in a mobile application that includes a webview, but we’re encountering some issues. Before diving into those, let’s provide some brief information:
- We are broadcasting from a React app within a WebView on both iOS and Android platforms, using the IVS Web Broadcast Client v1.5.2. We play the broadcast on both platforms by playing the associated .m3u8 file.
Here are the problems we are facing:
1. On the Android platform, we are getting different responses for different streamConfig settings.
    a. streamConfig->maxResolution -> We set width and height as 412*880, which we get from window.innerWidth and window.innerHeight,
    b. streamConfig->maxFramerate -> 30
    c. streamConfig->maxBitrate -> With resolution and FPS being constant; we have tried this with many values ranging from 1000 to 8500.
- In the above case, the broadcast doesn’t start at all. A session is created under the channel in IVS, but it cannot switch to LIVE status because;
    - According to IVS, video bitrate appears as 0 kbps, FPS is 0. Audio bitrate varies between 0-20kbps.
    - 11 seconds after reaching “Session Created” status, it enters the “Starvation Start” status.
- In this case, we tried many different values for maxResolution; the broadcast starts and flows smoothly with some, but the above situation occurs in others.
- Additionally, we couldn’t find a pattern among these values. Some examples are;
    - 720x1440 -> OK
    - 720x1350 -> FAIL
    - 600x1280 -> OK
    - 599x1280 -> FAIL
    - 720x1340 -> OK
- We conducted similar tests using a pure JS proof-of-concept (POC) on 6 different Android devices from various brands, such as Samsung, Xiaomi, and Oppo. Interestingly, some resolutions that generally fail were able to broadcast for a short duration (30-40 seconds) before entering “Starvation” status and dropping to 0 kbps bitrate. This was observed on a high-end Xiaomi Mi 12 Pro and a lower-end Samsung A33.
2. When watching the broadcast, the iOS platform always receives the broadcast with a delay of 5 to 10 seconds compared to the Android platform.
3. There is an audio-visual synchronization issue in the broadcast; we experienced an audio-visual lag problem as soon as the broadcast started on iPhone 11, with the following streamConfig settings:
    a. maxResolution -> 720x1280
    b. maxFramerate -> 30
    c. maxBitrate -> 2000

We need to find solutions for these problems as soon as possible and we would be very happy if you could help us.

**Comment by slee-aws** [comment]
Hi @alpgokcek - sorry to hear you are experiencing these issues with the broadcast SDK in your application's webview. Unfortunately, the web broadcast SDK currently does not fully support application webviews, as noted in the [broadcast SDK platform requirements](https://docs.aws.amazon.com/ivs/latest/LowLatencyUserGuide/broadcast.html#broadcast-webviews). Because of this, we may not be able to fully resolve your issue at this time.

For mobile implementations, we recommend the native iOS and Android broadcast SDKs. For sample code, refer to the native [iOS](https://github.com/aws-samples/amazon-ivs-broadcast-ios-sample) and [Android](https://github.com/aws-samples/amazon-ivs-broadcast-android-sample) repositories.

If you would like to seek further assistance on this topic, please open a support case with AWS Support or reach out and work with your AWS account team. If you neither have access to AWS Support and/or Account Teams, please post the question to [AWS re:Post](https://www.repost.aws/tags/TAAkUVScqiTFmkt-h6LdmJHw/amazon-interactive-video-service) where our developer advocates may provide additional insights. Thank you!
